{
 "title": "Compare Benchmark",
 "time": { "from": "2021-04-28T19:29:15.591Z", "to": "2021-04-28T20:07:01.543Z" },
 "templating": {
  "list": [
   { "name": "exec_uuid_1", "label": "exec_uuid_1", "query": { "query": "label_values(exec_uuid)" } },
   { "name": "exec_uuid_2", "label": "exec_uuid_2", "query": { "query": "label_values(exec_uuid)" } },
   { "name": "offset1", "label": "Offset 1", "query": "15s" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"} offset $offset1) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_1\"}[5m] offset $offset1)))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"} offset $offset1) by (cpu))",
     "legendFormat": "Exec 1 - $exec_uuid_1"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_2\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"}) by (cpu))",
     "legendFormat": "Exec 2 - $exec_uuid_2"
    }
   ]
  },
  {
   "title": "Average CPU usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"} offset $offset1) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_1\"}[5m] offset $offset1)))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\"} offset $offset1) by (cpu))",
     "legendFormat": "Exec UUID 1"
    },
    {
     "expr": "(((count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"} offset $offset1) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',exec_uuid=\"$exec_uuid_2\"}[5m] offset $offset1)))) * 100) / count(count(node_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\"} offset $offset1) by (cpu))",
     "legendFormat": "Exec UUID 2"
    }
   ]
  },
  {
   "title": "Busy CPU time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"} offset $offset1)",
     "legendFormat": "Exec 1"
    },
    {
     "expr": "sum(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_2\"})",
     "legendFormat": "Exec 2"
    }
   ]
  },
  {
   "title": "CPU busy time difference %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_2\"}[1h]))-sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1)))/sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1))*100",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU time VTGate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vtgate\"})",
     "legendFormat": "Exec 1"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vtgate\"})",
     "legendFormat": "Exec 2"
    }
   ]
  },
  {
   "title": "CPU time VTGate difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_2\"}[1h]))-sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1))\n",
     "legendFormat": "Time Difference Between Exec UUID 1 and Exec UUID 2"
    }
   ]
  },
  {
   "title": "CPU time VTGate difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_2\"}[1h]))-sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1)))/sum(increase(process_cpu_seconds_total{component=\"vtgate\", exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1))*100",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU usage Exec 1",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vtgate\"} offset $offset1)",
     "legendFormat": "VTGate"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"} offset $offset1)",
     "legendFormat": "VTTablet"
    }
   ]
  },
  {
   "title": "CPU usage Exec 2",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vtgate\"})",
     "legendFormat": "VTGate"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vttablet\"})",
     "legendFormat": "VTTablet"
    }
   ]
  },
  {
   "title": "CPU busy time difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_2\"}[1h]))-sum(increase(node_cpu_seconds_total{mode!=\"idle\",exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1))",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU time VTTablet",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"})",
     "legendFormat": "Exec 1"
    },
    {
     "expr": "sum(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vttablet\"})",
     "legendFormat": "Exec 2"
    }
   ]
  },
  {
   "title": "CPU time VTTablet difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_2\", component=\"vttablet\"}[1h]))-sum(increase(process_cpu_seconds_total{exec_uuid=\"$exec_uuid_1\", component=\"vttablet\"}[1h] offset $offset1))",
     "legendFormat": "Exec UUID 1"
    }
   ]
  },
  {
   "title": "CPU time VTTablet difference",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(process_cpu_seconds_total{component=\"vttablet\", exec_uuid=\"$exec_uuid_2\"}[1h]))-sum(increase(process_cpu_seconds_total{component=\"vttablet\", exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1)))/sum(increase(process_cpu_seconds_total{component=\"vttablet\", exec_uuid=\"$exec_uuid_1\"}[1h] offset $offset1))*100"
    }
   ]
  },
  { "title": "QPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "VTGate average QPS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(vtgate_api_count{exec_uuid=\"$exec_uuid_1\"}[1m] offset $offset1))",
     "legendFormat": "Exec 1 - $exec_uuid_1"
    },
    {
     "expr": "avg(rate(vtgate_api_count{exec_uuid=\"$exec_uuid_2\"}[1m]))",
     "legendFormat": "Exec 2 - $exec_uuid_2"
    }
   ]
  },
  {
   "title": "VTGate Queries Processed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(vtgate_queries_processed{exec_uuid=\"$exec_uuid_1\"} offset $offset1)",
     "legendFormat": "Exec 1 - $exec_uuid_1"
    },
    {
     "expr": "sum(vtgate_queries_processed{exec_uuid=\"$exec_uuid_2\"})",
     "legendFormat": "Exec 2 - $exec_uuid_2"
    }
   ]
  }
 ]
}